//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommuneCalculator.Pages.Roommates.CreateUpdate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateUpdateRoommateI18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateUpdateRoommateI18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommuneCalculator.Pages.Roommates.CreateUpdate.CreateUpdateRoommateI18n", typeof(CreateUpdateRoommateI18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelBtnContent {
            get {
                return ResourceManager.GetString("CancelBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or update a roommate.
        /// </summary>
        public static string CreateUpdateRoommateLblHeader {
            get {
                return ResourceManager.GetString("CreateUpdateRoommateLblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given name:.
        /// </summary>
        public static string FirstNameLbl {
            get {
                return ResourceManager.GetString("FirstNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is treasurer.
        /// </summary>
        public static string IsTreasurerLvl {
            get {
                return ResourceManager.GetString("IsTreasurerLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        public static string LastNameLbl {
            get {
                return ResourceManager.GetString("LastNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string LoginLbl {
            get {
                return ResourceManager.GetString("LoginLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move in:.
        /// </summary>
        public static string MoveInDateLbl {
            get {
                return ResourceManager.GetString("MoveInDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move out:.
        /// </summary>
        public static string MoveOutDateLbl {
            get {
                return ResourceManager.GetString("MoveOutDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordLbl {
            get {
                return ResourceManager.GetString("PasswordLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password repeat:.
        /// </summary>
        public static string PasswordRepeatLbl {
            get {
                return ResourceManager.GetString("PasswordRepeatLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveBtnContent {
            get {
                return ResourceManager.GetString("SaveBtnContent", resourceCulture);
            }
        }
    }
}
